package com.coder.gateway.views

import com.coder.gateway.cli.CoderCLIManager
import com.coder.gateway.sdk.v2.models.Workspace
import com.coder.gateway.sdk.v2.models.WorkspaceAgent
import com.jetbrains.toolbox.gateway.environments.SshEnvironmentContentsView
import com.jetbrains.toolbox.gateway.ssh.SshConnectionInfo
import java.net.URL
import java.util.concurrent.CompletableFuture

/**
 * A view for a single environment.  It displays the projects and IDEs.
 *
 * This just delegates to the SSH view provided by Toolbox, all we have to do is
 * provide the host name.
 *
 * SSH must be configured before this will work.
 */
class EnvironmentView(
    private val url: URL,
    private val workspace: Workspace,
    private val agent: WorkspaceAgent,
) : SshEnvironmentContentsView {
    override fun getConnectionInfo(): CompletableFuture<SshConnectionInfo> = CompletableFuture.completedFuture(object : SshConnectionInfo {
        /**
         * The host name generated by the cli manager for this workspace.
         */
        override fun getHost() = CoderCLIManager.getHostName(url, "${workspace.name}.${agent.name}")

        /**
         * The port is ignored by the Coder proxy command.
         */
        override fun getPort() = 22

        /**
         * The username is ignored by the Coder proxy command.
         */
        override fun getUserName() = "coder"
    })
}
